name: myntra_clone_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  get: ^4.6.5
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  google_fonts: ^3.0.1

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.webp
    - assets/images/drawer.jpg
    - assets/images/myntra_insider.jpg
    # rounded_images
    - assets/images/home_image/rounded_images/MEN.png
    - assets/images/home_image/rounded_images/WOMEN.png
    - assets/images/home_image/rounded_images/KID.png
    - assets/images/home_image/rounded_images/BEAUTY.png
    - assets/images/home_image/rounded_images/HOME.png
    - assets/images/home_image/rounded_images/JEWELLERY.png
    - assets/images/home_image/rounded_images/ESSENTIALS.png
    - assets/images/home_image/rounded_images/GADGETS.png
    #banner_images
    - assets/images/home_image/banner_images/banner1.png
    - assets/images/home_image/banner_images/banner2.png
    - assets/images/home_image/banner_images/banner3.webp
    - assets/images/home_image/banner_images/banner4.jpg
    - assets/images/home_image/banner_images/banner5.jpg
    # horizontal_banner_images
    - assets/images/home_image/horizontal_banner.jpg
    - assets/images/home_image/h_banner1.png
    - assets/images/home_image/h_banner2.png
    - assets/images/home_image/h_banner3.png
    - assets/images/home_image/h_banner4.png
    - assets/images/home_image/h_banner5.png
    - assets/images/home_image/h_banner6.png
    - assets/images/home_image/h_banner7.png
    - assets/images/home_image/h_banner8.png
    # categories_images
    - assets/images/categories/category1.png
    - assets/images/categories/category2.png
    - assets/images/categories/category3.png
    - assets/images/categories/category4.png
    - assets/images/categories/category5.png
    - assets/images/categories/category6.png
    - assets/images/categories/category7.png
    - assets/images/categories/category8.png
    - assets/images/categories/category9.png
    - assets/images/categories/category10.png
    - assets/images/categories/category11.png
    - assets/images/categories/category12.png
    # studio_rounded_images
    - assets/images/studio/rounded_images/rounded_image1.png
    - assets/images/studio/rounded_images/rounded_image2.png
    - assets/images/studio/rounded_images/rounded_image3.png
    - assets/images/studio/rounded_images/rounded_image4.png
    - assets/images/studio/rounded_images/rounded_image5.png
    # studio1_images
    - assets/images/studio/studio1_images/studio1_image.png
    - assets/images/studio/studio1_images/studio1_image1.png
    - assets/images/studio/studio1_images/studio1_image2.png
    - assets/images/studio/studio1_images/studio1_image3.png
    - assets/images/studio/studio1_images/studio1_image4.png
    - assets/images/studio/studio1_images/studio1_image5.png
    - assets/images/studio/studio1_images/studio1_image6.png
    - assets/images/studio/studio1_images/studio1_image7.png
    - assets/images/studio/studio1_images/studio1_image8.png
    # studio2_images
    - assets/images/studio/studio2_images/studio2_image.png
    - assets/images/studio/studio2_images/studio2_image1.png
    - assets/images/studio/studio2_images/studio2_image2.png
    - assets/images/studio/studio2_images/studio2_image3.png
    - assets/images/studio/studio2_images/studio2_image4.png
    # brand_men_home
    - assets/images/brand_home_images/round_image/round_image1.png
    - assets/images/brand_home_images/round_image/round_image2.png
    - assets/images/brand_home_images/round_image/round_image3.png
    - assets/images/brand_home_images/round_image/round_image4.png
    - assets/images/brand_home_images/round_image/round_image5.png
    - assets/images/brand_home_images/round_image/round_image6.png
    - assets/images/brand_home_images/round_image/round_image7.png
    - assets/images/brand_home_images/round_image/round_image8.png
    - assets/images/brand_home_images/round_image/round_image9.png
    - assets/images/brand_home_images/round_image/round_image10.png
    - assets/images/brand_home_images/round_image/banner.png

    - assets/images/brand_home_images/c_banner/c_banner1.png
    - assets/images/brand_home_images/c_banner/c_banner2.png
    - assets/images/brand_home_images/c_banner/c_banner3.png
    - assets/images/brand_home_images/c_banner/c_banner4.png
    - assets/images/brand_home_images/c_banner/c_banner5.png
    - assets/images/brand_home_images/c_banner/banner2.png

    - assets/images/brand_home_images/c2_banner/c2_banner1.png
    - assets/images/brand_home_images/c2_banner/c2_banner2.png
    - assets/images/brand_home_images/c2_banner/c2_banner3.png
    - assets/images/brand_home_images/c2_banner/c2_banner4.png
    - assets/images/brand_home_images/c2_banner/banner3.png

    - assets/images/brand_home_images/h_banner/h_banner1.png
    - assets/images/brand_home_images/h_banner/h_banner2.png
    - assets/images/brand_home_images/h_banner/h_banner3.png
    - assets/images/brand_home_images/h_banner/h_banner4.png
    - assets/images/brand_home_images/h_banner/h_banner5.png
    - assets/images/brand_home_images/h_banner/h_banner6.png
    - assets/images/brand_home_images/h_banner/banner4.png
    # t_shirt
    - assets/images/t_shirt/tshirt1.png
    - assets/images/t_shirt/tshirt2.png
    - assets/images/t_shirt/tshirt3.png
    - assets/images/t_shirt/tshirt4.png
    - assets/images/t_shirt/tshirt5.png
    - assets/images/t_shirt/tshirt6.png
    - assets/images/t_shirt/tshirt7.png
    - assets/images/t_shirt/tshirt8.png
    - assets/images/t_shirt/tshirt9.png
    - assets/images/t_shirt/tshirt10.png
    - assets/images/t_shirt/tshirt11.png
    - assets/images/t_shirt/tshirt12.png
    - assets/images/t_shirt/tshirt13.png
    - assets/images/t_shirt/tshirt14.png
    




    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
